---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: algo-arena-secret
spec:
  encryptedData:
    .env: AgByDEWso/Q7qd8hO5gvW9E4GlVfYgaYS122NHmk4gOD7KPKR3GvLxvziPadSA1S6zR0di72SUKuqQVSCFMkYZaKDdBboaGlin6+RxFR4DxSum0u0KArcruPwyS30SlPyjrCyxhSbhYVhMx8lYBxyYGSIURQf2PfzC1kdsBXEm6X7Xj5jOgq6cTBGxUjSN8ee6yM83/DzDcYfzWFr+yYtYBjz46oYeClSSbwWZb+Jm19dPENOlFM/UAt6CC2l+FEFt7x8DN8TOqTXynKw4BDB16TdAZ7vtswpgtzfIYA43scq6t2qv0sfF8iQ+uvplcM0St8JppxuIUEz0U19417bhutfvukYTEv3mtNMe4kYFptTmIRWjTKAxZB8bSawH7rjN0wUYhhJeW1piZX/QeOnKUUJC5BQYjU6P1eU4vBGfxCDoIi/tmCC40I5ppotk6zTg1s64cgi1n9rtrkkJkoMx1kMjxXwC0SdYGfpOkmE8z6TU4BmOAF/Sat5qRfqpqkQEhodzrRpetWoNNldNutUeWT1nZ4OUNI+oLTXNW6y0vH79yeeSlaW80fax9QCnbqK1X7b4DtiW0lUfFHlNXj/Q/RcFWIBVVTVwSwUm36XnX4guvZdUMgjcCV80u7PRlF3t6kju7kmE4KU27zppGV9W9kgpHWcQbP1hdOIPVBLkzI4h0cxL9KE/oj2F9snv0emXk=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: algo-arena-secret
    type: Opaque
